### ISSUE TITLE
to_json allows invalid JSON values: NaN, Infinity, -Infinity

### ISSUE THREAD

**Issue by davidcelis** [flori/json#140]
``` ruby

>> { :nan => Float::NAN }.to_json
=> "{\"nan\":NaN}"
>> JSON.parse "{\"nan\":NaN}"
JSON::ParserError: 209: unexpected token at 'NaN}'
from vendor/bundle/gems/json-1.7.3/lib/json/common.rb:155:in 'parse'
```

A similar issue arises if you have a mathematical expression that evaluates to `Infinity` or `-Infinity`. Perhaps NaN and +/-Infinity should be wrapped in quotes?

**Comment by stereobooster** [comment]
```ruby
irb(main):001:0> require "JSON"
=> true
irb(main):002:0> ::JSON.generate({ :nan => Float::NAN }, allow_nan: true)
=> "{\"nan\":NaN}"
```

Which is invalid [JSON](http://json.org/). It should be `"{\"nan\": \"NaN\"}"` or `"{\"nan\": null}"`. Otherwise third party parser (not ruby I mean) will fail to parse it.
