### ISSUE TITLE
Error installing gem under Ubuntu 12.04

### ISSUE THREAD

**Issue by allaud** [flori/json#169]
Catching this error under Ubuntu 12.04:

Building native extensions. This could take a while...
ERROR: Error installing json:
ERROR: Failed to build gem native extension.

/home/allaud/.rvm/rubies/ruby-1.9.3-p392/bin/ruby extconf.rb
creating Makefile

make
compiling generator.c
linking shared-object json/ext/generator.so
gcc: error: generator.o: No such file or directory
make: **\* [generator.so] Ошибка 1

Gem files will remain installed in /home/allaud/.rvm/gems/ruby-1.9.3-p392/gems/json-1.7.7 for inspection.
Results logged to /home/allaud/.rvm/gems/ruby-1.9.3-p392/gems/json-1.7.7/ext/json/ext/generator/gem_make.out

I am using fresh rvm and ruby 1.9.3 and have same trouble only with json gem. 

The error occurs when I try to execute:

```
gem install json
```

**Comment by codeadict** [comment]
same problem here, did u solved?

**Comment by allaud** [comment]
solved by using correct rvm environment and ruby version

**Comment by hsbt** [comment]
Ubuntu 12.04 is already EOL.
