### ISSUE TITLE
symbolize_names and create_additions do not play nice together

### ISSUE THREAD

**Issue by Kris-LIBIS** [flori/json#187]
Enabling the symbolize names option prevents the create_additions option from working. For example:

``` ruby
r = Range.new(0,8).to_json
  => "{\"json_class\":\"Range\",\"a\":[0,8,false]}"
JSON.parse r, create_additions: false
  => {"json_class"=>"Range", "a"=>[0, 8, false]}
JSON.parse r, create_additions: true
  => 0..8
JSON.parse r, create_additions: true, symbolize_names: true
  => {:json_class=>"Range", :a=>[0, 8, false]}
```

Combining both options is necessary if your code expects to end up with something like this:

``` ruby
{
    :query => {
        :location => {
            :x => 100..200,
            :y => 520..540
        }
    }
}
```

**Comment by lmrodriguezr** [comment]
@Kris-LIBIS thank you so much! I was scratching my head with `create_aditions` not working for a week, and now I know it was this interference you report with `symbolize_names`.

**Comment by perlun** [comment]
There is now error handling in place that detects this: https://github.com/flori/json/blob/master/lib/json/pure/parser.rb#L94-L96

I think this case can be closed @Kris-LIBIS or @flori, since combining them is (currently) an unsupported scenario.
