### ISSUE TITLE
Segmentation fault while running bundle exec rails server

### ISSUE THREAD

**Issue by tomaszwojcik** [flori/json#201]
After updating XCode to 5.1 and succesfuly installing gems (with ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future) I cannot run the Rails server.

System specs:
Mac OS X 10.9.2
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin13.1.0]
rails 4.0.3

I can provide crashlogs if needed.

-- Control frame information -----------------------------------------------
c:0018 p:-17576242688018 s:0063 e:000062 TOP    [FINISH]
c:0017 p:---- s:0061 e:000060 CFUNC  :require
c:0016 p:0009 s:0057 e:000056 TOP    /Users/twojcik/.gem/ruby/2.0.0/gems/pg-0.17.1/lib/pg.rb:4 [FINISH]
c:0015 p:---- s:0054 e:000053 CFUNC  :require
c:0014 p:0037 s:0050 e:000049 BLOCK  /Users/twojcik/.gem/ruby/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:76 [FINISH]
c:0013 p:---- s:0047 e:000046 CFUNC  :each
c:0012 p:0055 s:0044 e:000043 BLOCK  /Users/twojcik/.gem/ruby/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:72 [FINISH]
c:0011 p:---- s:0037 e:000036 CFUNC  :each
c:0010 p:0030 s:0034 e:000033 METHOD /Users/twojcik/.gem/ruby/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:61
c:0009 p:0013 s:0030 e:000029 METHOD /Users/twojcik/.gem/ruby/2.0.0/gems/bundler-1.5.3/lib/bundler.rb:131
c:0008 p:0073 s:0026 e:000025 TOP    /Users/twojcik/work/BinarySanctuary/hitorshit/config/application.rb:12 [FINISH]
c:0007 p:---- s:0024 e:000023 CFUNC  :require
c:0006 p:0014 s:0020 e:000019 BLOCK  /Users/twojcik/.gem/ruby/2.0.0/gems/railties-4.0.3/lib/rails/commands.rb:74 [FINISH]
c:0005 p:---- s:0017 e:000016 CFUNC  :tap
c:0004 p:0562 s:0014 e:000013 TOP    /Users/twojcik/.gem/ruby/2.0.0/gems/railties-4.0.3/lib/rails/commands.rb:71 [FINISH]
c:0003 p:---- s:0008 e:000007 CFUNC  :require
c:0002 p:0034 s:0004 E:000878 EVAL   bin/rails:4 [FINISH]
c:0001 p:0000 s:0002 E:0003e8 TOP    [FINISH]

**Comment by hsbt** [comment]
What's the issues related JSON gem? It's not JSON issues.
