### ISSUE TITLE
stop looking for files in /Users/travis

### ISSUE THREAD

**Issue by masukomi** [flori/json#207]
error message from installing the gem

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension
[skipping a bunch of lines]

make "DESTDIR="
compiling generator.c
linking shared-object json/ext/generator.bundle
ld: warning: directory not found for option '-L/Users/travis/.sm/pkg/active/lib'
```

Obviously i've got some other issues going on, but i'm pretty sure that under no circumstances should there be a hardcoded path for `/Users/travis` or anything else referencing `travis` during the install process.

As there's no travis user on my system I'm confident that that didn't come from anything I did.

**Comment by hsbt** [comment]
It's not json issue. Can you file it to provider of precompiled binary?
