### ISSUE TITLE
Issue parsing very large JSON file

### ISSUE THREAD

**Issue by Altonymous** [flori/json#208]
I have a very large JSON file and it appears to be having problems parsing it.  

Here's a gist of the file: https://gist.github.com/Altonymous/cfa9a4d8102287877d37

You'll need to make sure you view the raw.  It's all on one line, not formatted pretty.

I've tried 3 different ruby parsers with no luck.

However, jsonlint.com and python both are able to parse it.

Also of note it was python's JSON library that exported the file to being with.

I tried parsing it in irb:

```
file_path = "/temp/2014-06-24.json"
json = File.read(file_path)
hash = JSON.parse(json)
```

And the error I get is:

```
        JSON::ParserError: 757: unexpected token at '{"2269": {"recommended_pps": 360
        .
        .
        .
    from /Users/nunya/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/json/common.rb:155:in `parse'
    from /Users/nunya/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/json/common.rb:155:in `parse'
    from (irb):77
    from /Users/nunya/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
```

**Comment by ferventcoder** [comment]
So did you figure out the issue?
