### ISSUE TITLE
activating specific version of json gem?

### ISSUE THREAD

**Issue by ekremkaraca** [flori/json#216]
Hey guys,

I have an [issue here](https://github.com/jedcn/reveal-ck/issues/17) for a gem that is required specific version of json (1.7.7) gem. Until it's fixed, I'd like to switch this version of the gem. First, I've tried to uninstall latest version, but I got error because of being default gem. I've searched through internet for similar issues but there seems nothing close to mine.

What should I do?

**Comment by hsbt** [comment]
You can activate the specific version of json used by Bundler or `gem` method provided by RubyGems.

**Comment by ekremkaraca** [comment]
wow, it's been 7 years. thanks @hsbt !
