### ISSUE TITLE
Build fails with devkit on win32

### ISSUE THREAD

**Issue by andig** [flori/json#218]
This is the build error:

    C:\Users>gem install json
    ERROR:  Error installing json:
            ERROR: Failed to build gem native extension.

        C:/Ruby21/bin/ruby.exe extconf.rb
    creating Makefile

    make "DESTDIR=" clean

    make "DESTDIR="
    generating generator-i386-mingw32.def
    compiling generator.c
    cygwin warning:
      MS-DOS style path detected: C:/Ruby21/include/ruby-2.1.0/i386-mingw32
      Preferred POSIX equivalent is: /cygdrive/c/Ruby21/include/ruby-2.1.0/i386-mingw32
      CYGWIN environment variable option "nodosfilewarning" turns off this warning.
      Consult the user's guide for more details about POSIX paths:
        http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
    In file included from c:/Ruby21/include/ruby-2.1.0/ruby/ruby.h:24:0,
                     from c:/Ruby21/include/ruby-2.1.0/ruby.h:33,
                     from ../fbuffer/fbuffer.h:5,
                     from generator.c:1:
    C:/Ruby21/include/ruby-2.1.0/i386-mingw32/ruby/config.h:155:15: error: two or more data types in declaration specifiers
     #define uid_t int
                   ^
    C:/Ruby21/include/ruby-2.1.0/i386-mingw32/ruby/config.h:156:15: error: two or more data types in declaration specifiers
     #define gid_t int
                   ^
    In file included from c:/Ruby21/include/ruby-2.1.0/ruby/ruby.h:1694:0,
                     from c:/Ruby21/include/ruby-2.1.0/ruby.h:33,
                     from ../fbuffer/fbuffer.h:5,
                     from generator.c:1:
    c:/Ruby21/include/ruby-2.1.0/ruby/intern.h:318:72: warning: 'struct timeval' declared inside parameter list [enabled by default]
     int rb_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
                                                                            ^
    c:/Ruby21/include/ruby-2.1.0/ruby/intern.h:318:72: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
    In file included from c:/Ruby21/include/ruby-2.1.0/ruby/ruby.h:24:0,
                     from c:/Ruby21/include/ruby-2.1.0/ruby.h:33,
                     from ../fbuffer/fbuffer.h:5,
                     from generator.c:1:
    c:/Ruby21/include/ruby-2.1.0/ruby/intern.h:440:75: warning: 'struct timeval' declared inside parameter list [enabled by default]
     DEPRECATED(int rb_thread_select(int, fd_set *, fd_set *, fd_set *, struct timeval *));
                                                                               ^
    C:/Ruby21/include/ruby-2.1.0/i386-mingw32/ruby/config.h:107:52: note: in definition of macro 'DEPRECATED'
     #define DEPRECATED(x) __attribute__ ((deprecated)) x
                                                        ^
    In file included from c:/Ruby21/include/ruby-2.1.0/ruby/ruby.h:1694:0,
                     from c:/Ruby21/include/ruby-2.1.0/ruby.h:33,
                     from ../fbuffer/fbuffer.h:5,
                     from generator.c:1:
    c:/Ruby21/include/ruby-2.1.0/ruby/intern.h:441:79: warning: 'struct timeval' declared inside parameter list [enabled by default]
     int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
                                                                                   ^
    c:/Ruby21/include/ruby-2.1.0/ruby/intern.h:442:32: warning: 'struct timeval' declared inside parameter list [enabled by default]
     void rb_thread_wait_for(struct timeval);
                                    ^
    make: *** [generator.o] Error 1

    make failed, exit code 2

Looks like a C incompatibility with Windows, potentially like https://github.com/davidfstr/rdiscount/issues/74?

**Comment by qintaohao123** [comment]
The bug is fixed
