### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by niitotantei** [flori/json#240]
The file `ext/json/ext/generator/generator.c` has an additional restriction:

     * Unicode, Inc. hereby grants the right to freely use the information
     * supplied in this file in the creation of products supporting the
     * Unicode Standard, and to make copies of this file in any form
     * for internal or external distribution as long as this notice
     * remains attached.

which makes licensing of the software unclear and incompatible with GPL. Please fix this.

**Comment by flori** [comment]
The gem is ruby licenses, not GPL.

**Comment by niitotantei** [comment]
> The gem is ruby licenses, not GPL.

It's not Ruby-licensed anymore, since there is an additional restriction. Anyway, there is even an explicit relicensing clause in `COPYING` file:

> You can redistribute it and/or modify it under either the terms of the GPL
> (see GPL file), or the conditions below:

This is why I find licensing unclear.

The main issue here is, the additional restriction I mentioned before makes `generator.c` non-free software. The solution I think of would be to either ask the copyright owner to change the license or rewrite the code.

**Comment by flori** [comment]
Ah, I see. This is the text of the old ruby license, and it's not accurate anymore. The new text is https://www.ruby-lang.org/en/about/license.txt and BSD licensed. I think I will change this.
