### ISSUE TITLE
json-1.8.3 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by yashwinkumar** [flori/json#253]
Installing json 1.8.3 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/usr/local/rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150731-15743-prqh44.rb extconf.rb
```

Cannot allocate memory - /usr/local/rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150731-15743-prqh44.rb extconf.rb 2>&1

Gem files will remain installed in /home/projects/individ/releases/20150730121841/vendor/bundle/ruby/2.2.0/gems/json-1.8.3 for inspection.
Results logged to /home/projects/individ/releases/20150730121841/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.3/gem_make.out
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

**Comment by purezen** [comment]
I have the same issue. Am on Yosemite (Mac) and Ruby 2.2.2.

**Comment by alaouy** [comment]
The same issue on ubuntu-trusty-64 running ruby 2.2.3.

**Comment by snicky** [comment]
Thanks alaouy!

**Comment by sivagollapalli** [comment]
@alaouy Thanks.

**Comment by elcisko** [comment]
thanks!!!

**Comment by TakSuyu** [comment]
Having this problem with version 6.0.0-2 of gmp on Archlinux also

**Comment by jogaco** [comment]
Good tip!

**Comment by DRAKUN** [comment]
Hi i have the same problem on mac osx10.10 please someone can help , i search solution but i dont see nothing

**Comment by phsilbr** [comment]
Thanks a lot!

**Comment by manoevis** [comment]
thanks @alaouy :+1:

**Comment by gabrielmedina** [comment]
thanks!

**Comment by MannyCrisostomo** [comment]
Thanks @alaouy, God bless you man!

**Comment by xristos** [comment]
Hi,

I have the same exact problem in Windows7. Any help would be greatly appreciated! 

Thanks in advance!

**Comment by shabrin123** [comment]
thanks @alaouy :+1:

**Comment by FlintOFF** [comment]
thanks!

**Comment by shkurkin** [comment]
Thank you!!

**Comment by khanhpham1990** [comment]
Thank you.

**Comment by shabrin123** [comment]
Great

**Comment by noxious** [comment]
Thanks you too!

**Comment by ronyvieira** [comment]
Thank you @alaouy !

**Comment by Anyoks** [comment]
Thank you @alaouy ! That was really helpful. No other solution online worked!

**Comment by nazarok** [comment]
Thanks you too!

**Comment by zainalmustofa** [comment]
Woooww it's work, @alaouy Thanks.

**Comment by Karla-Isabel-Sandoval** [comment]
Thanks @alaouy your comment definitely got me on the right track. 

If..
bundle install will not work with if you because you recently updated to El Capitan 10.10
 Your error message will look like this: 
ERROR: "bundle install" was called with arguments ["json-1.8.3"] or this:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
To get around this issue try:

$xcode-select --install
$sudo chown -R (whoami):admin /usr/local
$sudo xcode-select --reset
$softwareupdate --install
$sudo xcodebuild -license

Then agree or disagree with Apples license.

**Comment by nvreynolds** [comment]
:bow:

**Comment by ajahongir** [comment]
:+1:

**Comment by Sunnepah** [comment]
Thanks @alaouy

**Comment by hamzouzou** [comment]
thanks

**Comment by miketuff20** [comment]
@alaouy I tried the command below but it says command not found.I have the El Capitan 10.10
sudo apt-get install libgmp3-dev
@Karla-Isabel-Sandoval .I tried the steps you gave and everything went smoothly but am getting some red text saying conflict 

 conflict  config/secrets.yml
Overwrite /Users/michaeltuffour/pinteresting/config/secrets.yml? (enter "h" for help) [Ynaqdh] h
        Y - yes, overwrite
        n - no, do not overwrite
        a - all, overwrite this and all others
        q - quit, abort
        d - diff, show the differences between the old and the new
        h - help, show this help
Overwrite /Users/michaeltuffour/pinteresting/config/secrets.yml? (enter "h" for help) [Ynaqdh] a
       force  config/secrets.yml

**Comment by Karla-Isabel-Sandoval** [comment]
Hi @miketuff20  Glad to hear the steps are working! One of Rails 4.1's main feature includes  config/secrets.yml.  The error message is asking you if you are ok generating a new secrets.yml file inside of config.You would have to go with the y - yes, overwrite option. Here is a link to help you make that decision:
'http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml'

Hope this helps :)

**Comment by miketuff20** [comment]
Thanks for your immediate response.It really helped.

**Comment by romikoops** [comment]
Thanks @Karla-Isabel-Sandoval

**Comment by khanhpham1990** [comment]
Good job. I had same error, but when i tried your solution, it worked very well.

**Comment by x-yuri** [comment]
First, let me cite typescript of what at least some of you experience, because the issue in original post is out of out of memory:

```
vagrant@vagrant-ubuntu-trusty-64:~$ gem install json
Fetching: json-1.8.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    /home/vagrant/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151114-7238-1rdvqi4.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
linking shared-object json/ext/generator.so
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [generator.so] Error 1

make failed, exit code 2

Gem files will remain installed in /home/vagrant/.rvm/gems/ruby-2.2.3/gems/json-1.8.3 for inspection.
Results logged to /home/vagrant/.rvm/gems/ruby-2.2.3/extensions/x86_64-linux/2.2.0/json-1.8.3/gem_make.out
```

And it can be remedied with `libgmp-dev`. Why `libgmp3-dev`? `json-1.8.3` depends on `/usr/lib/x86_64-linux-gnu/libgmp.so`, which is in [`libgmp-dev`][1].

[1]: http://packages.ubuntu.com/trusty/amd64/libgmp-dev/filelist

**Comment by raffe90** [comment]
@alaouy oh my god after a complete afternoon trying to fix this you have solved this for me, thank you so much

**Comment by walterjsilva** [comment]
Thanks @alaouy

**Comment by Eleventiy** [comment]
Thank You!

**Comment by olegsokolov513** [comment]
:+1:

**Comment by 7sedam7** [comment]
thanks

**Comment by izuo** [comment]
thanks.

**Comment by ayambao** [comment]
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

problem solved by alaouy.  

sudo apt-get install libgmp3-dev

Thanks :)

**Comment by Cendrao** [comment]
Thanks @alaouy ! Solved here too!

ubuntu 14.04 and Ruby 2.2.2

**Comment by sanjeev2838** [comment]
Thanks

**Comment by gpbonillas** [comment]
@alaouy Thanks! :+1:

**Comment by burdandrei** [comment]
@alaouy :100:

**Comment by KyleValentine** [comment]
Hello! i have the same issue on windows, is there a solution for windows? how can i install that library here?

**Comment by helloyokoy** [comment]
really thanks ~ it works~

**Comment by x-yuri** [comment]
@KyleValentine There are different issues discussed here. Which one do you experience? `Cannot allocate memory` as OP?

**Comment by Atul9** [comment]
@alaouy Thanks.

**Comment by PhucHoangHo** [comment]
Hi everyone. I am completely a beginner and this is a completely noob question. Like @alaouy suggested, I tried running sudo apt-get install libgmp3-dev in the command prompt and it returned:
'sudo' is not recognized as an internal or external command, operable program or batch file.
What am I doing wrong?

**Comment by x-yuri** [comment]
@PhucHoangHo Which distribution are you running? `cat /etc/issue`? `which apt-get`?

**Comment by PhucHoangHo** [comment]
@x-yuri I just run command prompt on my pc. I also have ruby 2.2.3 installed. I tried running ruby and put in the same command but it returned syntax error

**Comment by PhucHoangHo** [comment]
@x-yuri I have Windows 10, if that helps.

**Comment by x-yuri** [comment]
`apt-get` is `debian`'s package manager. That solution is for `linux`, not `windows`.

**Comment by PhucHoangHo** [comment]
@x-yuri in that case, do you know the solution for windows or where I can go find the solutions for windows? Thank you.

**Comment by melsatar** [comment]
@alaouy  Thanks!

**Comment by VernonGrant** [comment]
I had the same problem on Windows but solved it by doing the following. First make sure you have the development kit installed that you can download here: http://rubyinstaller.org/downloads/

Basically extract the devkit and cd into the folder and run the following commands:
1. ruby dk.rb init
2. ruby dk.rb install

You can find more information if needed about the installation procedure here: https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

After you have the devkit installed, install the json gem by running this command:
gem install json --platform=ruby

**Comment by volfgox** [comment]
Thanks!

**Comment by MarkOsipenko** [comment]
Thanks @alaouy

**Comment by iriver333** [comment]
Hello, I need a help. Alaouy's advice has helped many of you. And, I really want to follow @alaouy 's advice. But, I do not know how to do it.  I do not have much idea of using "command prompt" but after following instructions from  " https://www.youtube.com/watch?v=hy5x8aGKrrw ", I began to use it. But, this YOUTUBE link does not tell me how to apply @alaouy 's advice. Is there anyone who could explain how I apply " sudo apt-get install libgmp3-dev " to my command prompt? 

When I simply typed it after "c:\row\dev\mysql_test>" I only received an error message. 

Help me please! *^^*

**Comment by alu0100505023** [comment]
Thanks!

**Comment by MarkOsipenko** [comment]
sorry, i don't know, correct answer for you question.
I think,Windows haven't command sudo apt-get install libgmp3-dev, you need
find same command, but for Windows OS.
Solution "sudo apt-get install libgmp3-dev" working on Ubuntu

**Comment by Tushar-H** [comment]
Thanks @alaouy.

**Comment by byzg** [comment]
@alaouy thanks a lot! Works for ruby 2.1.8, Ubuntu 14.04

**Comment by betoharres** [comment]
didn't work

**Comment by apolloclark** [comment]
"sudo apt-get install -y libgmp3-dev"
is not working with Debian Jessie, ruby version:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by x-yuri** [comment]
@apolloclark Since you've got separate issue, not the one being discussed here.

**Comment by ergouge** [comment]
$ sudo apt-get install ruby-dev
or
$ sudo yum install ruby-devel
if you’re using Redhat distro, or
$ sudo zypper install ruby-devel
if you are using [open]SuSE.

the answer  really hit my problem.  try the link blow for more details.
http://stackoverflow.com/questions/20559255/error-while-installing-json-gem-mkmf-rb-cant-find-header-files-for-ruby

**Comment by apolloclark** [comment]
@ergouge Thanks for the help! I already have ruby-env installed in Debian. I'm not a ruby developer, I just use it as a dependency for another program. I'm guessing this json gem is incompatible with the latest ruby 2.3 in rbenv.

**Comment by venelrene** [comment]
apt-get: command not found
I'm running on ruby 
-/.rvm/rubies/ruby-2.3.0/bin/ruby
on OS X Captain

**Comment by yoyocoder** [comment]
`sudo gem install -n /usr/local/bin json` if you are on osx

**Comment by courthead** [comment]
On OSX, I just opened up Xcode, clicked "I agree", then closed Xcode and I was able to install my gem just fine.

**Comment by acbilimoria** [comment]
@alaouy  solved it for me too!  Digital Ocean one click Rails app, Ubuntu 14.04  + Ruby 2.2.3

**Comment by pulkit21** [comment]
Thanks @alaouy

**Comment by emobile** [comment]
God bless you @alaouy one hug

**Comment by solutionize-parthiban** [comment]
Thanks @alaouy

**Comment by januszm** [comment]
This still is a problem with Ruby 2.2.5 and Mac OS X 10.11 , any solution other than (re)installing the full Xcode package? I only have Xcode command-line tools installed.

**Comment by chadjoseph** [comment]
@januszm I'm on OS X 10.11.4, with full Xcode 7.3.1, Ruby 2.2.5 and this is still a problem for me as well. I've tried the Mac suggestions above and installing GMP separately but I have not found a solution yet.

**Comment by TracKer** [comment]
I was having the same problem on Windows 10, but rolling back **Ruby** to version **2.2.4** solved the problem.

**Comment by harokevin** [comment]
@VernonGrant Worked for Windows 8. Unzip the file anywhere you want, I did "C:\RubyDevKit", and then go into that file in command line(using cd) and run: `ruby dk.rb init` followed by `ruby dk.rb install`
Again, it doesn't matter where you put the file. I was worried I would have to put it somewhere into my Ruby installation but this is not true. Many thanks! I hope this comment helps someone.

**Comment by shireeshj** [comment]
This command did the trick for me

```sh
brew install coreutils
```

ruby 2.2.5 with rvm on macOS El Capitan

**Comment by romenigld** [comment]
@shireeshj worked for me.
`brew install coreutils`
 ruby 2.2.5p319
Rails 4.2.5.2 
OS: El Capitan Mac Os X.

**Comment by gpashokgp** [comment]
installing ruby-dev helped me on ubuntu14.04

**Comment by amitdotagarwal** [comment]
brew install coreutils, for OSX user

**Comment by JulienBreux** [comment]
_Note for the futures readers:_

If you work with AlpineLinux image for Docker.

Use this packages to build natives extensions: `curl-dev ruby-dev build-base`.

#KISS

**Comment by gulnara** [comment]
for OS X users:
`brew install coreutils`
then it installs without issues. Make sure you have your command line tools installed and agreed to terms and conditions of the license.

**Comment by ChristopherJoonMiller** [comment]
on osx 10.10.5, rbenv, ruby 2.3.0
coreutils didn't do it for me... this did:

```
xcode-select --install
sudo xcodebuild -license
```

then I had a separate problem with postgresql, had to specify arch flags during gem install and then bundle install: `ARCHFLAGS="-arch x86_64" bundle install`

**Comment by migs120** [comment]
simple fix delete your gem.lock file and run bundle install this should rebuild the gemlock file and fix the issue, i was getting the same error when trying to move my development environment from nitrous.io to cloud9,. hope this help

**Comment by chestarss** [comment]
thanks for @ergouge

**Comment by Juice007** [comment]
if you are in MacOS Sierra and your ruby version is 2.4.0.The ruby version is not compatible with json 1.8.3. You can try add this line in your Gemfile: 
```
gem 'json', github: 'flori/json', branch: 'v1.8'
```
This works for me!

**Comment by wellington1993** [comment]
Thanks for @Juice007!

**Comment by elearningz** [comment]
Thanks @Juice007 worked like a charm with 2.4.0 on Sierra for me as well.

**Comment by elbertwang** [comment]
@Juice007 it works!! Thank you.

**Comment by amanuelg** [comment]
Thanks @shireeshj 
`brew install coreutils`  
worked for Ruby 2.2.5 and MacOS Sierra.

**Comment by bradpurchase** [comment]
Thank you @Juice007, works!

**Comment by carc1n0gen** [comment]
@migs120 yup that was the fix for me.  My ruby version didn't seem to be compatible with the old version of json

**Comment by mrzool** [comment]
@Juice007 that finally fixed it for me on Mac OS El Capitan. Thanks.

**Comment by berchan** [comment]
thanks for @Juice007

**Comment by vhosakot** [comment]
I saw the error `Failed to build gem native extension` too on CentOS 7.3 and vagrant 1.8.7.

I resolved it after installing ruby-devel and gcc (`yum -y install ruby-devel gcc`)

**Comment by kevindelord** [comment]
On my side, I had to do the following to solve this issue:

- update `RVM` to the latest stable version
```
curl -sSL https://get.rvm.io | bash -s stable --ruby
source /Users/kevindelord/.rvm/scripts/rvm 
```
- reinstall `bundler`
```
gem install bundler
```
- Force the `json` version to `~> 1.8.5` in the Gemfile as it was link to its `1.8.3` version by the gem `github-pages`, and then bundle install again!
```
bundle update json
bundle install
````

**Comment by baruchvlz** [comment]
I got this error using Docker
OS: Ubuntu 17.04
Ruby: 2.4.1
Rails: ~>5

I fixed it two different ways, one was what @kevindelord suggested, I added `RUN bundle update json` to the `Dockerfile`, looks something like so:

```
FROM ubuntu:17.04
FROM ruby:2.4.1

USER root
RUN apt-get update

# removed 10 lines for readability purposes

RUN gem install bundler
# Force use of json > 1.8.3
RUN bundle update json
RUN bundle install
```

The other way was adding `gem 'json', github: 'flori/json', branch: 'v1.8'` to the `Gemfile` as suggested by @Juice007 a few months ago.

**Comment by cfsanderson** [comment]
Thanks @kevindelord ! worked great on macOS 10.12.4 - Ruby 2.4.1

**Comment by molopez** [comment]
I'm on OSX Sierra

`bundle update json` from @kevindelord. This worked for me.

**Comment by wtmatthias** [comment]
thanks @Juice007. most helpful. worked on Mac OS X El Capitan 10.11.6 with  Ruby 2.4.0

**Comment by Gnodiah** [comment]
`bundle update json` fixed the issue

**Comment by zhaoye159** [comment]
I am a noob in ruby and I saw @Juice007 's method helps a lot of people then I really want to give a try. But really not sure how to add a line in my gemfile. Do I need to run something in terminal to open and edit the file? or follow the direction locally and edit in a file whose name is "Gemfile". If it's the second one, I found not only one file whose name is "Gemfile", then which one should I choose?

**Comment by bradpurchase** [comment]
@zhaoye159 open the `Gemfile` in your project root and add the line to it using your editor of choice. You will then need to run `bundle install` on the command line.

**Comment by roshan92** [comment]
`bundle update json` fixed the issue on macOS 10.13 - Ruby 2.4.1

**Comment by kemerydev** [comment]
Running on OSX Sierra, this was not fixable with xcode-select (for me), but downgrading my ruby version from 2.4.1 to 2.3.4 fixed it

**Comment by entity1991** [comment]
@alaouy, thanks)

**Comment by tinodau** [comment]
Thanks @alaouy :D

**Comment by iWeslie** [comment]
Thanks @kevindelord I have finally solved the problem.    
`brew install coreutils` doesn't work on my macOS and I don't know why.    
but, after `bundle update json` and `bundle install` , it worked and there is no error like the following any more.    

```
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

**Comment by BjornMelgaard** [comment]
Does anyone knows solution for archlinux? What package I have to install instead of `sudo apt-get install libgmp3-dev`?

P.S. tried `yaourt lib32-gmp4` - no luck

**Comment by tangguochang** [comment]
thanks for help!  @vhosakot

**Comment by yhk1038** [comment]
Following @Juice007, in MacOS Sierra, the ruby version 2.4.0 is not compatible with json 1.8.3.

Add this line at before your crash:
`gem 'json', github: 'flori/json', branch: 'v1.8'`
then `bundle install`

It works for me very well.
thanks @Juice007

**Comment by gnfisher** [comment]
For Arch Linux users (cc @BjornMelgaard):

`sudo pacman -S mpfr` 

should do the trick.

**Comment by bsurnida** [comment]
Thanks @alaouy

**Comment by danielhaim1** [comment]
`brew install coreutils` didn't do the trick and `gem uninstall json` won't do either because it's a default gem. try `bundle update json` and then run `bundle install`, that could work.

**Comment by cythilya** [comment]
@danielhaim1 Thanks :)

**Comment by xiaotianhu** [comment]
Either Ruby or gem is new to me.
On Macos,I use brew to install ruby and gem,but by default brew cannot replace the ruby bin file which system already has;And `brew link ruby --force` said you should do:
` export PATH="/usr/local/opt/ruby/bin:$PATH"
 export LDFLAGS="-L/usr/local/opt/ruby/lib"
 export CPPFLAGS="-I/usr/local/opt/ruby/include"
`
This finally works on my Mac,whish this could help for newbies.

**Comment by hsbt** [comment]
You should upgrade json-1.8.5+ or the stable versions of Ruby like 2.5 or 2.6.

**Comment by MeetChavda** [comment]
> Thanks @alaouy your comment definitely got me on the right track.
> 
> If bundle install will not work for you because you recently updated to El Capitan 10.10
> Your error message will look like this:
> 
> `ERROR: "bundle install" was called with arguments ["json-1.8.3"]` or this:
> `Gem::Ext::BuildError: ERROR: Failed to build gem native extension`
> 
> To get around this issue try:
> 
> $xcode-select --install
> $sudo chown -R (whoami):admin /usr/local
> $sudo xcode-select --reset
> $softwareupdate --install
> $sudo xcodebuild -license
> 
> Then agree or disagree with Apples license.

*and  what about ubuntu???*
