### ISSUE TITLE
1.8.3 not compatible with ruby version 2.2.3

### ISSUE THREAD

**Issue by dansteele** [flori/json#259]
As much as I tried, I could not get this json gem to build the native gem extensions under ruby 2.2.3. Clean installs etc.
Works fine with 2.2.2

**Comment by tenderlove** [comment]
Can you post the errors you're getting?

**Comment by efalkner** [comment]
Hello, I am seeing the same issue. I've added the error we're seeing here: 

```
[2015-10-19T10:36:56-04:00] ERROR: gem_package[json] had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/gem install json -q --no-rdoc --no-ri -v "1.8.3" --no-rdoc --no-ri ----
STDOUT: Building native extensions.  This could take a while...
STDERR: ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20151019-19723-j4rnoj.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.2.0/gems/json-1.8.3 for inspection.
Results logged to /var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.3/gem_make.out
---- End output of /usr/bin/gem install json -q --no-rdoc --no-ri -v "1.8.3" --no-rdoc --no-ri ----
Ran /usr/bin/gem install json -q --no-rdoc --no-ri -v "1.8.3" --no-rdoc --no-ri returned 1
[2015-10-19T10:36:57-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by dansteele** [comment]
This is the same error I get.

**Comment by efalkner** [comment]
Based on some research I've found that there's a ruby dev-kit, which, when installed, will make the install successful. 
`apt-get install ruby2.2-dev ` installed the dev kit for me.
The package, 'libgmp3-dev' was installed by the dev kit, but it looks like you should be able to install just libgmp3-dev. Here's a link to the issue I found: https://github.com/flori/json/issues/253. Not sure how to link issues in the github project.

**Comment by crabonature** [comment]
Indeed installing this package
```$ sudo apt-get install libgmp3-dev```
 will resolve problem. Got the same error some time ago with clean Ruby 2.2.3 installed by RVM.

**Comment by dedevillela** [comment]
Thanks for the tip! Can someone please explain how to install libgmp3-dev on Ruby running Win7?
Best regards,

**Comment by naveed-ahmad** [comment]
`sudo apt-get install libgmp3-dev` fixed issue for ruby 2.2.4 and json 1.8.3 as well.

**Comment by januszm** [comment]
What about Mac OS X ? (10.11, Ruby 2.2.5 installed with RVM)

```shell
make "DESTDIR=" install
make: /usr/local/bin/gmkdir: No such file or directory
make: *** [.RUBYARCHDIR.time] Error 1

make install failed, exit code 2
```

**Comment by nathanpaul** [comment]
Confirmed still getting this issue with OSX 10.11 and Ruby 2.2.5

**Comment by vizjerai** [comment]
OS X 10.11 and ruby 2.2.5 works after running

`brew install coreutils`

**Comment by amicming** [comment]
Thanks @vizjerai, working fine with OS X 10.11 and ruby 2.2.5

**Comment by infernalsirius** [comment]
Same here, `brew install coreutils` did the trick. Thx @vizjerai

**Comment by hsbt** [comment]
You should upgrade json-1.8.5+ or the stable versions of Ruby like 2.5 or 2.6.
