### ISSUE TITLE
json-1.8.3 is failing to install with ruby 2.0.0p647 (2015-08-18) [x64-mingw32] (Windows 10)

### ISSUE THREAD

**Issue by amitkayal** [flori/json#264]
json 1.8.3 is failing with following error. My ruby version is 2.0.

F:\Amit\Ruby\Ruby200-x64>gem install json -v ='1.7.1'
Fetching: json-1.7.1.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

```
F:/Amit/Ruby/Ruby200-x64/bin/ruby.exe extconf.rb
```

creating Makefile

make "DESTDIR=" clean

make "DESTDIR="

make failed, exit code 5

Gem files will remain installed in F:/Amit/Ruby/Ruby200-x64/lib/ruby/gems/2.0.0/gems/json-1.7.1 for inspection.
Results logged to F:/Amit/Ruby/Ruby200-x64/lib/ruby/gems/2.0.0/extensions/x64-mingw32/2.0.0/json-1.7.1/gem_make.out

F:\Amit\Ruby\Ruby200-x64>gem install json
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

```
F:/Amit/Ruby/Ruby200-x64/bin/ruby.exe extconf.rb
```

creating Makefile

make "DESTDIR=" clean

make "DESTDIR="

make failed, exit code 5

Gem files will remain installed in F:/Amit/Ruby/Ruby200-x64/lib/ruby/gems/2.0.0/gems/json-1.8.3 for inspection.
Results logged to F:/Amit/Ruby/Ruby200-x64/lib/ruby/gems/2.0.0/extensions/x64-mingw32/2.0.0/json-1.8.3/gem_make.out

**Comment by hsbt** [comment]
Ruby 2.0 is EOL at 2020.

**Comment by marcandre** [comment]
@hsbt The current gemspec states `required_ruby_version >= '2.0'` (after #415) and travis tests run on Ruby 2.0.

I believe the actual reason for closing this issue is that json-1.x is no longer supported, right?

**Comment by hsbt** [comment]
Yes. I have no motivation about that.
