### ISSUE TITLE
error in installing bundle in ruby on rail

### ISSUE THREAD

**Issue by psprincesaini9** [flori/json#266]
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that gem install json -v '1.8.3' succeeds before bundling.

problem while bundle install i am using window 10 please help

**Comment by fengyuxx** [comment]
try this:
sudo apt-get install ruby1.9.1-dev

**Comment by hsbt** [comment]
Ruby 1.9 and json-1.8.3 is EOL now. You should upgrade Ruby or json-1.8.5+
