### ISSUE TITLE
please release new version (v1.8.5) due to license issues

### ISSUE THREAD

**Issue by lksv** [flori/json#280]
I found out that all the released version (e.g. last is 1.8.3) has "old" ruby license (e.g. GPL).
Currently in the master is already used current ruby version (BSD compatible).

By my opinion (and I am not lawer), the "old" ruby license is copyleft license and this gem cannot be included in other gems under MIT licence (activesupport, sidekiq, carrierwave and others). It seams that a lot of other gem's (which are MIT) do not mention it and includes this gem.

If you be so kind and release new version, it could makes non-confilicting most of the other gems (all which do not put version condition in .gemspec file).

**Comment by perlun** [comment]
[v1.8.6](https://rubygems.org/gems/json/versions/1.8.6) has now been released.

@flori or anyone else, please close this issue, since it has been settled.
