### ISSUE TITLE
to_json result can't be parsed by JSON.parse

### ISSUE THREAD

**Issue by smrt28** [flori/json#285]
Hi,

When I create a sting by to_json method, should always be possible to parse that sting by JSON.parse?

JSON.parse("aa".to_json)

the result is an exception "unexpected token". Maybe, it's by design, but IMO the parser should be able to parse json string created by the library itself  otherwise it looks funny.

According to RFC https://tools.ietf.org/html/rfc7159 (paragraph 2. JSON Grammar), the behavior seems to be deprecated and the parser should accept a string as valid json. 

ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
json (1.8.3, 1.8.1)

**Comment by nicosuave** [comment]
@smrt28 Use the `quirks_mode` option to allow for parsing of naked primitives i.e. `JSON.parse("aa".to_json, quirks_mode: true)`

I submitted a PR (https://github.com/ruby/ruby/pull/1391), but I'm not exactly sure where to add the documentation in this repository, as suggested per @hsbt comment.

**Comment by flori** [comment]
Please try a JSON version >= 2.
