### ISSUE TITLE
JSON.load("null") raises exception 

### ISSUE THREAD

**Issue by ali-l** [flori/json#291]
Accidentally upgraded `json_pure` from `1.8.3` to `2.0.1` and noticed that it now raises an error when calling `JSON.load` with `"null"`. 

Is this a bug or a change in behaviour?

**Comment by flori** [comment]
It works here:

```
(flori@hacmaxi:~ ↳0)$ irb
>> gem 'json_pure', '2.0.2'
 # => true
>> require 'json/pure'
 # => true
>> JSON.load 'null'
 # => nil
>> JSON.parser
 # => JSON::Pure::Parser
```

Can you give me a minimal code example that shows the problem? What does `JSON.parser` return?
