### ISSUE TITLE
Gem only works with ruby 2.0

### ISSUE THREAD

**Issue by andrewlarssen** [flori/json#297]
The gem now only works with Ruby 2.0. Ideally it should work with 2.0+

This is due to the required_ruby_version in the gem spec:
json/json.gemspec:21
```
s.required_ruby_version = Gem::Requirement.new("~> 2.0".freeze)
```

Can it be relaxed to:

```
s.required_ruby_version = Gem::Requirement.new(">= 2.0".freeze)
```

**Comment by flori** [comment]
`~> 2.0` means `>= 2.0` and `< 3`. It's probably a while until ruby 3.0 is released, and I surely will check if JSON is supported then and change the requirement in time.
