### ISSUE TITLE
A z release that bumps required ruby version

### ISSUE THREAD

**Issue by cyberious** [flori/json#298]
Requiring ruby 2.0 on a `z` release after not requiring any version of ruby on previous release is against semvar and as a result is now breaking our test cases against Ruby 1.9.3 (yes I know it is deprecated)  This should have been a major version bump to add that as a requirement.

**Comment by flori** [comment]
I consider it to be more of a bug fix for the 2.0.0 version.

**Comment by cyberious** [comment]
That may be the case, however changing a requirement such as minimum version of ruby requires a major version bump. Bundler should respect that and fall back to the last major version as long as it also meets the requirements.  Unless it is absolutely necessary to have Ruby 2.0 with the latest version of json_pure than it should be reverted and added to your 3.0 release when you plan that.

**Comment by flori** [comment]
See https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by cyberious** [comment]
The above does not change the fact that changing the minimum requirement requires a major version bump even if it was EOL for that version.

**Comment by cyberious** [comment]
http://semver.org as well as specifically http://semver.org/#spec-item-9 which states 
```
Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug 
fixes are introduced. A bug fix is defined as an internal change that fixes incorrect 
behavior.
```
