### ISSUE TITLE
Ruby 2.4.0 with RoR 3.2.xx, 4.2.xx bundle install fail

### ISSUE THREAD

**Issue by Sega100500** [flori/json#308]
Error:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/home/ruby/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20161225-17221-ivjmjg.rb extconf.rb
creating Makefile

current directory: /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function ‘generate_json’:
generator.c:861:25: error: ‘rb_cFixnum’ undeclared (first use in this function)
     } else if (klass == rb_cFixnum) {
                         ^
generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:863:25: error: ‘rb_cBignum’ undeclared (first use in this function)
     } else if (klass == rb_cBignum) {
                         ^
generator.c: At top level:
cc1: warning: unrecognized command line option "-Wno-self-assign"
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
Makefile:241: ошибка выполнения рецепта для цели «generator.o»
make: *** [generator.o] Ошибка 1

make failed, exit code 2

Gem files will remain installed in /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-1.8.3 for inspection.
Results logged to /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

**Comment by Sega100500** [comment]
https://github.com/rails/rails/issues/27450

**Comment by alepore** [comment]
try using `gem 'json', github: 'flori/json', branch: 'v1.8'`

**Comment by Sega100500** [comment]
@alepore 
It works. Thanks!
But! Used 1.8.5
Can you publish last version of gem '1.8' - to '1.8.5' ?

**Comment by alepore** [comment]
@Sega100500 also, are you aware that the json gem is already included in ruby 1.9.3+?
Try removing the whole dependency, if possible

**Comment by Sega100500** [comment]
@alepore 
Where dependency?! In Ruby on Rails?!!

**Comment by Sega100500** [comment]
@alepore 
> try using gem 'json', github: 'flori/json', branch: 'v1.8'

It possible for few projects... But I have too many projects on RoR 3.2.xx and 4.2.xx
Edit each Gemfile - it no resolve a problem

**Comment by Sega100500** [comment]
@alepore 
gem 1.8.3 has an error. In use with Ruby 2.4.0
Please FIX IT.
