### ISSUE TITLE
Parsing JSON with `quirks_mode: false` parses as if it is `true` and does not warn me.

### ISSUE THREAD

**Issue by JoshCheek** [flori/json#309]
Originally posted at https://bugs.ruby-lang.org/issues/13070

-----

Previously you could parse toplevel strings in JSON by setting `:quirks_mode` to `true`. If you set it to `false`, it would not parse them.

```ruby
`ruby -v`                                      # => "ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin15]\n"
require "json"                                 # => true
JSON.parse JSON.dump("a"), quirks_mode: true   # => "a"
JSON.parse JSON.dump("a"), quirks_mode: false  # ~> JSON::ParserError: 784: unexpected token at '"a"'
```

In Ruby 2.4.0, it always parses them, no matter how I set `:quirks_mode`, but it does not warn me that it is going to ignore my instruction to disallow this behaviour.

```ruby
`ruby -v`                                      # => "ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]\n"
require "json"                                 # => true
JSON.parse JSON.dump("a"), quirks_mode: true   # => "a"
JSON.parse JSON.dump("a"), quirks_mode: false  # => "a"
```

I think it should warn me as explicitly setting it to `false` implies that I rely on this behaviour (this was my case).

The changelog should probably also mention something about it, I didn't understand what had happened until I [located the commit](https://github.com/ruby/ruby/commit/1130658), looked up its references, realized the specification may have changed, and then checked the RFC.

**Comment by flori** [comment]
The RFC changed and parsing non-object or non-array JSON values is always allowed now.

**Comment by cben** [comment]
The commit removing it is 7d2ad6d6556da03300a5aeadeeacaec563435773
See also #206

**Comment by JoshCheek** [comment]
Then, how about raising an explanatory error, if I pass `quirks_mode: false`?

**Comment by Nakilon** [comment]
For anyone who comes around thinking he's going crazy:
this exception also happens if you add `json_pure` to `Gemfile` but use `require "json"`.
