### ISSUE TITLE
v1.8.5 has not been published to rubygems

### ISSUE THREAD

**Issue by redox** [flori/json#311]
Any chance you guys could publish `json@1.8.5` to rubygems?

This will probably fix #303 #308 #280

**Comment by Lordnibbler** [comment]
+1

**Comment by Drenmi** [comment]
+1 on behalf of every Rails 4.2 user. 😊

**Comment by anatol** [comment]
`metasploit` software also depends on `json-1.8.x` and fails to install at ruby-2.4.

json 1.8.x is still actively used by many packages and it needs to be supported at ruby-2.4 as well. Please release json-1.8.x that is fixed for ruby-2.4. Thank you in advance.

**Comment by redox** [comment]
Awesome, thanks @flori 👍
