### ISSUE TITLE
Infinity and NaN dump but don't parse

### ISSUE THREAD

**Issue by mperham** [flori/json#312]
Should the .dump call immediately raise an error?

```ruby
a = {}
a['inf'] = 1.0/0.0
a['nan'] = 0.0/0.0
str = JSON.dump(a)
puts str
# {"inf":Infinity,"nan":NaN}
JSON.parse(str)
# => JSON::ParserError: 230: unexpected token at ':Infinity,"nan":NaN}'
```

JSON::VERSION => 2.0.2
ruby -v => ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]

**Comment by mperham** [comment]
```ruby
> JSON.dump_default_options
=> {:max_nesting=>false, :allow_nan=>true}
```

This might be a Ruby integration issue: `lib/ruby/2.4.0/json/common.rb` has allow_nan default to true when calling `dump` but uses the default value (false) when calling `parse`.

**Comment by flori** [comment]
The dump/load interface uses allow_nan, while the generate/parse interface doesn't. The use case for dumping and loading is (de-)serialisation into a database (like Marshal does) while generate/parse is for communicating via standard json to other parties' clients.

**Comment by mperham** [comment]
Thank you @flori!
