### ISSUE TITLE
Segmentation Fault when trying to start rails server after upgrading to rails 2.4 and json 1.8.5

### ISSUE THREAD

**Issue by raonibr** [flori/json#315]
Hey guys! I'm trying to bump my rails project to ruby 2.4.0; For that, I had to update json to 1.8.5.
It bundles fine, but when I try to start the rails server, I get:

`/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0032 p:-17560706059086 s:0095 e:000094 TOP    [FINISH]
c:0031 p:---- s:0093 e:000092 CFUNC  :require
c:0030 p:0009 s:0089 e:000088 CLASS  /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json/ext.rb:13
c:0029 p:0011 s:0087 e:000086 CLASS  /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json/ext.rb:12
c:0028 p:0057 s:0085 e:000084 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json/ext.rb:9 [FINISH]
c:0027 p:---- s:0083 e:000082 CFUNC  :require
c:0026 p:0019 s:0079 e:000078 CLASS  /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json.rb:58
c:0025 p:0017 s:0077 e:000076 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json.rb:54 [FINISH]
c:0024 p:---- s:0075 e:000074 CFUNC  :require
c:0023 p:0007 s:0071 e:000070 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:2 [FINISH]
c:0022 p:---- s:0069 e:000068 CFUNC  :require
c:0021 p:0079 s:0065 e:000064 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/activesupport-4.2.4/lib/active_support/core_ext/object.rb:12 [FINISH]
c:0020 p:---- s:0063 e:000062 CFUNC  :require
c:0019 p:0015 s:0059 e:000058 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/configuration.rb:2 [FINISH]
c:0018 p:---- s:0057 e:000056 CFUNC  :require
c:0017 p:0015 s:0053 e:000052 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/railtie.rb:2 [FINISH]
c:0016 p:---- s:0051 e:000050 CFUNC  :require
c:0015 p:0007 s:0047 e:000046 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/engine.rb:1 [FINISH]
c:0014 p:---- s:0045 e:000044 CFUNC  :require
c:0013 p:0055 s:0041 e:000040 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/application.rb:7 [FINISH]
c:0012 p:---- s:0039 e:000038 CFUNC  :require
c:0011 p:0063 s:0035 e:000034 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails.rb:11 [FINISH]
c:0010 p:---- s:0033 e:000032 CFUNC  :require
c:0009 p:0031 s:0029 e:000028 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/server.rb:4 [FINISH]
c:0008 p:---- s:0027 e:000026 CFUNC  :require
c:0007 p:0014 s:0023 e:000022 METHOD /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123
c:0006 p:0015 s:0019 e:000018 METHOD /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:73
c:0005 p:0033 s:0016 e:000015 METHOD /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39
c:0004 p:0116 s:0012 e:000011 TOP    /Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands.rb:17 [FINISH]
c:0003 p:---- s:0008 e:000007 CFUNC  :require
c:0002 p:0034 s:0004 E:0025a8 EVAL   bin/rails:4 [FINISH]
c:0001 p:0000 s:0002 E:0001f8 TOP    [FINISH]

bin/rails:4:in `<main>'
bin/rails:4:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:73:in `server'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/server.rb:4:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/commands/server.rb:4:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails.rb:11:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails.rb:11:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/application.rb:7:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/application.rb:7:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/engine.rb:1:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/engine.rb:1:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/railtie.rb:2:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/railtie.rb:2:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/configuration.rb:2:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/railties-4.2.4/lib/rails/configuration.rb:2:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/activesupport-4.2.4/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/activesupport-4.2.4/lib/active_support/core_ext/object.rb:12:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:2:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:2:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json.rb:54:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json.rb:58:in `<module:JSON>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json.rb:58:in `require'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json/ext.rb:9:in `<top (required)>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json/ext.rb:12:in `<module:JSON>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json/ext.rb:13:in `<module:Ext>'
/Users/raoni/.rvm/gems/ruby-2.4.0-rc1/gems/json-1.8.5/lib/json/ext.rb:13:in `require'`

**Comment by bmurtagh** [comment]
I'm experiencing similar segfaults on Ruby 2.4.0 (installed via RVM) and json gem v2.0.3:

```/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0014 p:-17548412065898 s:0058 e:000057 TOP    [FINISH]
c:0013 p:---- s:0056 e:000055 CFUNC  :require
c:0012 p:0115 s:0052 e:000051 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0011 p:0009 s:0042 e:000041 CLASS  /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:7
c:0010 p:0011 s:0040 e:000039 CLASS  /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:6
c:0009 p:0017 s:0038 e:000037 TOP    /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:3 [FINISH]
c:0008 p:---- s:0036 e:000035 CFUNC  :require
c:0007 p:0115 s:0032 e:000031 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0006 p:0019 s:0022 e:000021 CLASS  /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json.rb:59
c:0005 p:0017 s:0020 e:000019 TOP    /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json.rb:55 [FINISH]
c:0004 p:---- s:0018 e:000017 CFUNC  :require
c:0003 p:0115 s:0014 e:000013 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0002 p:0015 s:0004 E:000468 EVAL   ./getJenkinsMetrics.rb:4 [FINISH]
c:0001 p:0000 s:0002 E:0025e8 TOP    [FINISH]

./getJenkinsMetrics.rb:4:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json.rb:55:in `<top (required)>'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json.rb:59:in `<module:JSON>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:3:in `<top (required)>'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:6:in `<module:JSON>'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:7:in `<module:Ext>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: ./getJenkinsMetrics.rb

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
   10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
   11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
   12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
   13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
   18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/path_support.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb
   20 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb
   21 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/command.rb
   22 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/core_ext/hash_with_indifferent_access.rb
   23 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/core_ext/ordered_hash.rb
   24 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/error.rb
   25 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/invocation.rb
   26 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser/argument.rb
   27 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser/arguments.rb
   28 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser/option.rb
   29 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser/options.rb
   30 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser.rb
   31 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/shell.rb
   32 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/line_editor/basic.rb
   33 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/readline.bundle
   34 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/line_editor/readline.rb
   35 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/line_editor.rb
   36 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/util.rb
   37 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/base.rb
   38 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor.rb
   39 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/version.rb
   40 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/ostruct.rb
   41 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/generic_object.rb
   42 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/common.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6```

**Comment by mrpinsky** [comment]
I'm also running into something similar with v2.1.0 on Ruby 2.4:

```
/usr/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156: [BUG] Segmentation fault at 0x00007f0045505954
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0021 p:---- s:0130 e:000129 CFUNC  :parse
c:0020 p:0025 s:0126 e:000125 METHOD /usr/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156
/lib/polleverywhere.rb:63
/lib/polleverywhere.rb:25 [FINISH]
c:0017 p:0122 s:0111 e:000110 METHOD /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7/lib/em/deferrable.rb:151
c:0016 p:0014 s:0103 e:000102 METHOD /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7/lib/em/deferrable.rb:191
c:0015 p:0135 s:0098 e:000097 METHOD /usr/lib/ruby/gems/2.4.0/gems/em-http-request-1.1.5/lib/em-http/client.rb:113
c:0014 p:0028 s:0092 e:000091 METHOD /usr/lib/ruby/gems/2.4.0/gems/em-http-request-1.1.5/lib/em-http/client.rb:71
c:0013 p:0043 s:0088 e:000087 BLOCK  /usr/lib/ruby/gems/2.4.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:137 [FINISH]
c:0012 p:---- s:0084 e:000083 CFUNC  :<<
c:0011 p:0014 s:0079 e:000078 METHOD /usr/lib/ruby/gems/2.4.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:152
c:0010 p:0012 s:0072 e:000071 METHOD /usr/lib/ruby/gems/2.4.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:23 [FINISH]
c:0009 p:---- s:0067 e:000066 CFUNC  :run_machine
c:0008 p:0327 s:0063 e:000062 METHOD /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195
c:0007 p:0036 s:0055 e:000054 METHOD /usr/lib/ruby/gems/2.4.0/gems/kingkong-1.0.1/lib/kingkong/runner.rb:70
c:0006 p:0009 s:0050 E:001578 METHOD /usr/lib/ruby/gems/2.4.0/gems/kingkong-1.0.1/lib/kingkong/runner.rb:51
.rb:134 [FINISH]
c:0004 p:---- s:0023 e:000022 CFUNC  :require
c:0003 p:0132 s:0018 e:000017 METHOD /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
c:0002 p:0030 s:0006 e:000005 EVAL   ./bin/pollev-ping-runner:5 [FINISH]
c:0001 p:0000 s:0003 E:001810 (none) [FINISH]
```

**Comment by hsbt** [comment]
Ruby 2.4 is EOL at 2020. Can you update your Ruby with Ruby 2.5+? Thanks.

**Comment by marcandre** [comment]
The actual feedback is not that Ruby 2.4 is EOL, but that this should be attempted with the latest release of `json` 2.3.0

If there is a segfault with Ruby 2.4 and the latest `json`, please let us know.
