### ISSUE TITLE
An error occurred while installing json (1.8.6), and Bundler cannot continue

### ISSUE THREAD

**Issue by medito** [flori/json#326]
Hi
I'm trying to install plugin in redmine 3.3.2-2 but in my installation the plugin told to update bundle
in start of upadate, I have this error (json did not installed): 
_FYI : I'll try to install 'sudo apt-get install libgmp3-dev' but with any result_
`bundle update json
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies......
Using rake 12.0.0
Using i18n 0.8.0
Installing json 1.8.6 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/redmine/redmine-3.3.2-2/ruby/bin/ruby extconf.rb
creating Makefile

make "DESTDIR=" clean
sh: 1: make: not found

make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /home/redmine/redmine-3.3.2-2/ruby/lib/ruby/gems/2.1.0/gems/json-1.8.6 for inspection.
Results logged to /home/redmine/redmine-3.3.2-2/ruby/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/json-1.8.6/gem_make.out
An error occurred while installing json (1.8.6), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.6'` succeeds before bundling.
`
Thanks a lot

**Comment by tapickell** [comment]
Seeing the same on issue Linux, works fine on OSX though.

**Comment by medito** [comment]
Hello,
Thanks a lot
But in Debian doesn't work 
finally, I found the solution with uninstalling all Bitnami Redmine package, and I install redmine from scratch and the last version of ruby 2.3.4, and I installed json -v '1.8.6', now everything is OK.
Cause of problem : version of ruby 2.0.1 doesn't support json.

Best regards.
