### ISSUE TITLE
about the license

### ISSUE THREAD

**Issue by rainchen** [flori/json#337]
This project is using "Ruby License", but "Ruby License" is not a standard license name, Ruby is using [BSD 2-Clause License](https://opensource.org/licenses/BSD-2-Clause) and [explanation](https://choosealicense.com/licenses/bsd-2-clause/) .

Let's make open source work fun and pro.

**Comment by drujensen** [comment]
What is the license for this repo?  I need this in order to use your GEM.

**Comment by hsbt** [comment]
"Ruby License" is valid name with SPDX identifiers.

https://spdx.org/licenses/Ruby.html
