### ISSUE TITLE
The common interface tests test undefined behavior

### ISSUE THREAD

**Issue by nirvdrum** [flori/json#343]
Commit 79074a0de768113364749cb584000b7e97be04e5 introduced tests for the library's common interface. Unfortunately, one of the newly added tests is for undefined behavior in Ruby. In Ruby, as in most other languages, `NaN` != `NaN`:

```
> ruby -v -e 'p Float::NAN == Float::NAN'
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
false
```

However, `NaN` being tested inside of an array is undefined behavior per https://bugs.ruby-lang.org/issues/1720. On recent Ruby releases that means you can and do have the current behavior:

```
> ruby -v -e 'p [Float::NAN] == [Float::NAN]'
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
true
```

That wrapping the `NaN` value in an array suddenly allows it to become equal to itself is really just an optimization decision that MRI has made. To account for the contradiction, the comparison of `NaN` inside an array is declared as undefined and the result of such a comparison is subject to change in future Ruby versions and allowed to be different across Ruby implementations.

The test in issue is:

```
def test_parse_bang
  assert_equal [ 1, NaN, 3, ], JSON.parse!('[ 1, NaN, 3 ]')
end
```

While this test is using `JSON::NaN` instead of `Float::NAN`, they are represented by the same floating point value. Thus, this test relies on undefined behavior.

**Comment by hsbt** [comment]
This issue was resolved at https://github.com/flori/json/commit/565c72ba9e70f4262e66dd33fffb307711d6de27 maybe.
