### ISSUE TITLE
ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by prateek121** [flori/json#350]
+ gem install json -v 2.1.0
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h
  

ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

**Comment by olleolleolle** [comment]
This is about the Ruby language's header files not being available. (It's not a defect of `json`. I'll try to explain.)

In Linux distributions, there's often a `-dev` variant of software packages (like Ruby).

Here's an example of such a package: https://packages.debian.org/stretch/ruby-dev

In the section "Installing the packages", Brightbox explains more about the relationship between `rubyNN` and `rubyNN-dev` where `NN` stands for a Ruby release version.
https://www.brightbox.com/docs/ruby/ubuntu/

Can this Issue be closed, now?
