### ISSUE TITLE
json-2.1.0 is failing to install with ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32] (Windows 10)

### ISSUE THREAD

**Issue by AndressaKarla** [flori/json#353]
json-2.1.0 is failing to install with ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32] (Windows 10):

λ gem install json -v '2.1.0'
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180514-6536-ugko1.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean
'make' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
'make' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.

make failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/json-2.1.0/gem_make.out

**Comment by sandeepnagra** [comment]
+1

I see 2 versions with 2.1.0 and the latest one appears to be with JRuby  and older one with Ruby extension of C

This is a blocker for us.
