### ISSUE TITLE
Problem install JSON on UBUNTU 18.04

### ISSUE THREAD

**Issue by trocolit2** [flori/json#357]
Hi,
I installed a fresh new UBUNTU 18.04, and I am facing errors during json installation.
After ran the `gem install json` command I got the error shown in follow 
```
$ sudo gem install json
Building native extensions. This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/json-2.1.0/ext/json/ext/generator
/usr/bin/ruby2.5 -r ./siteconf20180620-12452-uyviq.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/json-2.1.0 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/json-2.1.0/gem_make.out
```
For Ubuntu 18.04, the ruby version is 2.5.
Could any one gives me tips to solve this issue?
I can provide more detailed information if needed.

Thanks in advance.

**Comment by guygastineau** [comment]
You should be able to `require 'json'` at the top of your file without installing any gems.

#### If you do need the gem for some reason
- I don't think you need to use `sudo` to execute `gem install json`

- Did you try it without sudo?

**Comment by guygastineau** [comment]
- Seeing the contents of that `gem_make.out` file where the results were logged would be really helpful.

- To reiterate though, I believe json is now built in to Ruby. If you're on 2.5.0 a simple `require 'json'` with no gem installation should be fine.

**Comment by jmcclare** [comment]
I had the same issue on Ubuntu 18.04. From what I can tell this is not an issue with the JSON Ruby gem. This is more of a documentation and Ruby system setup issue.

You need to install the `ruby-dev` package to get the header files it’s looking for.

Do the following.

```bash
sudo apt install -y ruby dev
sudo gem install json
```

It should install and install and build its extensions without issue.

Installing `ruby-dev` should be the standard instructions for setting up Ruby on Ubuntu.
