### ISSUE TITLE
json/ext handles isolated escaped surrogates inconsistently

### ISSUE THREAD

**Issue by mernen** [flori/json#38]
Using json 1.4.3, Ruby 1.8.7p174 and 1.9.2-preview1.

When given a high surrogate with no low surrogate, it gives `nil` for the string:

```
JSON.parse(%q{[123,"x\uD834x"]}    # => [123, nil]
```

When given a low surrogate with no high surrogate, it treats it as a valid character:

```
JSON.parse %q{[123,"x\uDD5Ex"]}    # => [123, "x\355\265\236x"]
```

In both cases, `json/pure` throws `JSON::GeneratorError`s due to iconv's strictness (`IllegalSequence` on OS X, `InvalidCharacter` on Linux).

**Comment by hsbt** [comment]
Ruby 1.x is EOL at 2020.
