### ISSUE TITLE
Provide a `load_file` method like YAML's

### ISSUE THREAD

**Issue by keithrbennett** [flori/json#386]
One very common use case is to need to parse the contents of a JSON file.

As far as I know, this can only be accomplished in 2 steps, e.g. `JSON.parse(File.read('something.json'))`.

YAML provides a convenient `load_file` method that combines these two. Obviously, it is trivially simple to implement.

Could we get a similar method (preferably with the same name) in this JSON library?

**Comment by hsbt** [comment]
https://github.com/flori/json/pull/387 was merged now.
