### ISSUE TITLE
Missing json_pure v2.3.0 gem

### ISSUE THREAD

**Issue by glennsarti** [flori/json#393]
It seems json v2.3.0 was released, however there was no accompanying json_pure gem release.

Commit https://github.com/flori/json/commit/38f68d1e05174fa466dcabbc924d2098f0d8b824 suggests there should indeed be a 2.3.0 release of json_pure.

**Comment by hsbt** [comment]
https://rubygems.org/gems/json_pure/versions/2.3.0
