### ISSUE TITLE
Expected ParseError for pure ruby variant

### ISSUE THREAD

**Issue by bjfish** [flori/json#394]
Steps to reproduce:
`ruby -rjson/pure -e 'p JSON.parse("{")'`

Expected:
` unexpected token at '{' (JSON::ParserError)`

Actual:
`{}`

**Comment by eregon** [comment]
See https://github.com/oracle/truffleruby/issues/1570#issuecomment-568171114 for the original issue (TruffleRuby uses json/pure currently).

So this is an issue of the pure version accepting input that the C-ext does not accept.

**Comment by marcandre** [comment]
Duplicate of #314
