### ISSUE TITLE
json 1.8.6 produces a deprecation on ruby 2.7

### ISSUE THREAD

**Issue by scudco** [flori/json#399]
https://github.com/flori/json/blob/7f4cfd853f2c919d854fb95548a19980feff17e8/lib/json/common.rb#L155

This line produces the following deprecation message:
```
<snip>/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
```

It'd be nice to get a patch-level bump to silence this particular deprecation.

**Comment by mike-loopvoc** [comment]
This same problem occurs in version 2.2.  What is strange is that it appears to be immune to setting RUBYOPT='-W:no-deprecated -W:no-experimental' - the deprecation messages print like crazy anyway (and I have seen it suppress the same messages from every other source that was producing them.)

**Comment by leoplct** [comment]
+1 It prints everywhere

**Comment by rdp** [comment]
Please it's so chatty...

**Comment by hsbt** [comment]
I'm not sure what maintenance status about v1.8 by flori as primary owner.

At least, I have no plan to maintain json-1.8.x in 2020. I suggest to upgrade json-2.3.0

**Comment by bengalamx** [comment]
Any solutions?

**Comment by hsbt** [comment]
Use json-2.x.

**Comment by joevandyk** [comment]
There's a lot of gems that still require json ~> 1.8... would be very nice to have a 1.8.7 that fixes this particular warning.

**Comment by airblade** [comment]
Using Rails, this seems to get rid of the warnings:

```ruby
# config/initializers/json.rb
module JSON
  module_function

  def parse(source, opts = {})
    Parser.new(source, **opts).parse
  end
end
```

**Comment by joemsak** [comment]
@airblade For me, your solution was no dice :(

**Comment by andregit1** [comment]
> Using Rails, this seems to get rid of the warnings:
> 
> ```ruby
> # config/initializers/json.rb
> module JSON
>   module_function
> 
>   def parse(source, opts = {})
>     Parser.new(source, **opts).parse
>   end
> end
> ```

you're solutions really saved my day !

**Comment by gentaro-sakamoto** [comment]
ref. https://github.com/flori/json/releases/tag/v2.3.0
