### ISSUE TITLE
Properly Serialize OpenStructs

### ISSUE THREAD

**Issue by yagudaev** [flori/json#403]
Serializing OpenStructs leads to unexpected results.

```ruby
[OpenStruct.new(a: 1), {b: 2}, {c: 3}].as_json
=> NoMethodError (undefined method `as_json' for [#<OpenStruct a=1>, {:b=>2}, {:c=>3}]:Array)
```

There is a whole thread about in on Stackoverflow here: https://stackoverflow.com/a/13777745/1321251.

We should attempt to prevent this type of confusing behavior and fix the issue to serialize only the items inside of `table`.

**Comment by marcandre** [comment]
You must load the relevant addition:

```
require "json/add/ostruct"
OpenStruct.new(a: 1).as_json # => {"json_class"=>"OpenStruct", "t"=>{:a=>1}} 
```
