### ISSUE TITLE
Better test coverage

### ISSUE THREAD

**Issue by mernen** [flori/json#41]
The library needs more extensive testing. Through bug reports on json-jruby, I've noticed the following parts are not covered:
- Bignums
- Non-UTF strings
- Strings with isolated surrogates (see issue #38)
- `Generator::State` getters and setters (settings are always being passed on initialization)
- Strings whose internal buffer offset is nonzero (a rather specific implementation detail, but could be useful nonetheless), i.e.:
    str = 'xx["foobar"]'
    substr = str[2..-1]
    JSON.parse(substr)  # confuses json-jruby 1.1.5

**Comment by hsbt** [comment]
We welcome to your patch for test coverage.
