### ISSUE TITLE
Does not follow Ruby 1.9 syntax

### ISSUE THREAD

**Issue by swenson** [flori/json#410]
This gem is listed as source compatible with 1.9, but it causes a syntax error when run in ruby 1.9.

The line is: https://github.com/flori/json/blob/master/lib/json/common.rb#L156

```ruby
Parser.new(source, **(opts||{})).parse
```

When run in ruby 1.9.0, for example:

```
 irb(main):002:0> Parser.new(source, **(opts||{})).parse
SyntaxError: (irb):2: syntax error, unexpected tPOW
Parser.new(source, **(opts||{})).parse
```

This appears to come from this commit:
https://github.com/flori/json/commit/bbc88248581fb3c7063edd9fae00af5f7d1f18d9

**Comment by hsbt** [comment]
Ruby 1.9 is EOL. This code is valid after Ruby 2.0.
