### ISSUE TITLE
json.gemspec

### ISSUE THREAD

**Issue by marcandre** [flori/json#417]
I am wondering if #398 is this the right way to go.

Current gemspec is error prone as the files are listed explicitly instead of generated on the fly.

It is also confusing that `json_pure.gemspec` is generated automatically and not `json.gemspec`.

Either #398 is reverted (and control character?? fixed) or else the gemspec should be cleaned up.

**Comment by hsbt** [comment]
In last year, I have not a owner grant of `json_pure`. Now, I can release `json` and `json_pure`. We will replace `json_pure.gemspec` same as `json.gemspec`.

**Comment by hsbt** [comment]
@marcandre I think the current gemspecs have no issues. So, I will close this.
