### ISSUE TITLE
Wrong number of arguments for dump in 2.7.0

### ISSUE THREAD

**Issue by MihaiOnSoftware** [flori/json#555]
In our code base we have a call to the gem that looks like this:

```
JSON.dump(timestamp: datetime.to_s, log_type: "generic", message: msg).concat("\n")
```

We end up calling that line indirectly in a spec with data that makes it into:

```
JSON.dump(timestamp: "12342", log_type: "generic", message: "test").concat("\n")
```

We just upgraded to 2.7.0 today and it leads to the following error from inside the JSON gem:

```
ArgumentError:
  wrong number of arguments (given 0, expected 1..3)
/usr/local/bundle/gems/json-2.7.0/lib/json/common.rb:614:in `dump'
```

Please let me know if you need any more information.

**Comment by MihaiOnSoftware** [comment]
It seems that wrapping the arguments into a hash solves the issue:
```
JSON.dump({ timestamp: datetime.to_s, log_type: "generic", message: msg }).concat("\n")
```

If that's intentional it might make sense to include it in the compatibility changes

**Comment by MihaiOnSoftware** [comment]
Looks like this was fixed here https://github.com/flori/json/issues/553

**Comment by MihaiOnSoftware** [comment]
https://github.com/flori/json/issues/553

**Comment by hsbt** [comment]
@jcoyne We need to another fix like https://github.com/flori/json/pull/558. After that, I'll release the new version.
