### ISSUE TITLE
Sorting an Object's Keys for Serialization

### ISSUE THREAD

**Issue by yfeldblum** [flori/json#58]
There are cases where it is useful to serialize objects/hashes with their keys in some particular well-known order such as lexicographical sorted order.

This is useful when we are storing the output of a JSON-serialized data structure in a file and including that file in version control. Chef needs to do exactly this scenario this for a variety of tasks (http://tickets.opscode.com/browse/CHEF-1972).

Some implementations of Ruby return an object's/hash's keys in one order, while other implementations of Ruby return them in another. This creates problems when two computers with differing versions of Ruby save the same JSON-serialized data structure in a file, because the two files will be different. For example, this could result in extraneous commits, merge conflicts, or extra work to `git-checkout` files where only the ordering of the keys was changed.

An option to sort keys by some sorter such as lexicographical would be very useful for these types of applications/libraries.

**Comment by segiddins** [comment]
There is a standard for this, https://www.rfc-editor.org/rfc/rfc8785
