### ISSUE TITLE
Json open source license issue

### ISSUE THREAD

**Issue by nareshcool97** [flori/json#592]
json Ruby license
License
https://spdx.org/licenses/Ruby.html

Detailed paths
Introduced through: project@* › newrelic_plugin@1.3.1 › json@2.7.2
Fix: No remediation path available.
Introduced through: project@* › rubocop@1.59.0 › json@2.7.2
Fix: No remediation path available.
Introduced through: project@* › rubocop-faker@1.1.0 › rubocop@1.59.0 › json@2.7.2
Fix: No remediation path available.

**Comment by hsbt** [comment]
I'm not sure what's a problem.
