### ISSUE TITLE
Error installing json 1.5.3

### ISSUE THREAD

**Issue by ghost** [flori/json#78]
Using RVM
Mac OS X 10.6.7
Ruby 1.9.2 

$ gem update json
Updating installed gems
Updating json
Building native extensions.  This could take a while...
ERROR:  Error installing json:
    ERROR: Failed to build gem native extension.

```
    /Users/georgegithinji/.rvm/rubies/ruby-1.9.2-p180/bin/ruby extconf.rb
```

checking for re.h... no
checking for ruby/st.h... yes
creating Makefile

**Comment by j1wilmot** [comment]
Ran into this issue today and it was indeed related to an old macports install. Solution from @alexch worked for me. Thanks! This blog post was also relevant: http://thoughtsthatleakedout.blogspot.com/2011/10/problem-with-gmkdir-when-updating-gems.html

**Comment by mxchai** [comment]
@j1wilmot thanks for the link buddy. I cannot express how much gratitude I have towards you.

**Comment by mtjhax** [comment]
`brew update; brew install coreutils` was all it took for me after installing Ruby 2.2.5 with RVM and getting the same error on json.

**Comment by alexey** [comment]
had exactly the same situation like @mtjhax, thanks buddy for help!

**Comment by robertkesek** [comment]
Uoa, after 3hours of trying different things. I finally got to install compass.
Thank you @mtjhax!!!
