### ISSUE TITLE
Invalid gemspec on rubygems 1.8.6

### ISSUE THREAD

**Issue by ajsharp** [flori/json#99]
I see this when I install (and when other gems depend on) json under rubygems 1.8.6:

Invalid gemspec in [/Users/ajsharp/.rvm/gems/ruby-1.9.2-p290@connie/specifications/json-1.6.1.gemspec]: invalid date format in specification: "2011-09-18 00:00:00.000000000Z"

**Comment by hsbt** [comment]
RubyGems 1.x is EOL status in 2021.
